spring.application.name=cartapp
server.port=8084

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:free
spring.datasource.username=system
spring.datasource.password=root
product.service.url=http://localhost:8083/grocers/api/products
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
