server.port=8086
spring.application.name=requestapp
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:free
spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
spring.datasource.username=system
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

services.products-url=http://localhost:8083/grocers/api/products

