import { useEffect, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import axios from "axios";
import { ArrowRight, CircleHelp, KeyRound, LockKeyhole, Mail, ShieldCheck, Sparkles } from "lucide-react";
import api, { errorMessage } from "../config/api";

const labels: Record<string, string> = { FIRST_PET_NAME: "What was your first pet's name?", FIRST_SCHOOL_NAME: "What was your first school's name?", CHILDHOOD_NICKNAME: "What was your childhood nickname?" };
const Input = (p: React.InputHTMLAttributes<HTMLInputElement>) => <input {...p} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 p-3.5 font-normal outline-none transition focus:border-app-green focus:bg-white"/>;

export default function SecurityQuestionRecovery() {
  const [params] = useSearchParams(); const navigate = useNavigate();
  const [email, setEmail] = useState(params.get("email") || ""), [question, setQuestion] = useState(""), [answer, setAnswer] = useState(""), [token, setToken] = useState(""), [password, setPassword] = useState(""), [confirm, setConfirm] = useState(""), [loading, setLoading] = useState(Boolean(params.get("email"))), [error, setError] = useState("");
  const step = token ? 3 : question ? 2 : 1;
  useEffect(() => { if (!email) { setLoading(false); return; } setLoading(true); setError(""); api.get<string>("/auth/locked-account/security-question", { params: { email } }).then(({ data }) => setQuestion(data)).catch(e => { if (axios.isAxiosError(e) && e.response?.status === 409) navigate(`/unlock-account?email=${encodeURIComponent(email)}`, { replace: true }); else setError(errorMessage(e, "We could not start secure recovery for this account.")); }).finally(() => setLoading(false)); }, [email, navigate]);
  const verify = async (e: React.FormEvent) => { e.preventDefault(); try { const { data } = await api.post<{ resetToken: string }>("/auth/locked-account/verify-security-answer", { email, answer }); setToken(data.resetToken); setAnswer(""); toast.success("Identity confirmed."); } catch (err) { toast.error(errorMessage(err, "Your answer needs employee review.")); navigate(`/unlock-account?email=${encodeURIComponent(email)}`, { replace: true }); } };
  const reset = async (e: React.FormEvent) => { e.preventDefault(); if (password.length < 8) return setError("Choose a password with at least 8 characters."); if (password !== confirm) return setError("Those passwords do not match yet."); try { await api.post("/auth/locked-account/reset-password", { email, resetToken: token, newPassword: password }); localStorage.removeItem("grocers_recovery_email"); toast.success("Password updated — you can sign in now."); navigate("/auth", { replace: true }); } catch (err) { setError(errorMessage(err, "Your reset expired. Please start again.")); } };
  const form = !email ? <form onSubmit={e => { e.preventDefault(); navigate(`/recover-account?email=${encodeURIComponent(email)}`, { replace: true }); }} className="mt-8 space-y-5"><label className="block text-sm font-semibold text-slate-700">Email address<Input required autoFocus type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="action">Continue securely <ArrowRight size={18}/></button></form> : loading ? <div className="py-16 text-center"><span className="mx-auto grid size-14 animate-pulse place-items-center rounded-2xl bg-lime-100 text-app-green"><LockKeyhole/></span><h2 className="mt-6 font-serif text-3xl">Preparing your recovery</h2><p className="mt-3 text-sm text-slate-500">One moment while we protect your account.</p></div> : error && !question ? <div className="rounded-2xl border border-rose-100 bg-rose-50 p-6"><h2 className="font-serif text-3xl">We need a little help</h2><p className="mt-3 text-sm leading-6 text-rose-800">{error}</p><Link to="/auth" className="mt-6 inline-flex font-bold text-app-orange">Back to sign in <ArrowRight className="ml-2" size={16}/></Link></div> : token ? <form onSubmit={reset} className="space-y-5"><p className="eyebrow">Step 3 of 3</p><h2 className="title">Create a fresh password</h2><p className="copy">Make it memorable to you, and at least 8 characters long.</p><label className="field">New password<Input required autoFocus type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Create a new password"/></label><label className="field">Confirm new password<Input required type="password" value={confirm} onChange={e => setConfirm(e.target.value)} placeholder="Type it once more"/></label>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button className="action">Save new password <ArrowRight size={18}/></button></form> : <form onSubmit={verify} className="space-y-6"><p className="eyebrow">Step 2 of 3</p><h2 className="title">A quick question for you</h2><p className="copy">This is the question you chose when you created your account.</p><div className="rounded-2xl border border-lime-200 bg-lime-50 p-5"><CircleHelp className="text-app-green" size={22}/><p className="mt-3 text-lg font-semibold leading-7 text-[#183b2b]">{labels[question] || question}</p></div><label className="field">Your answer<Input required autoFocus type="password" value={answer} onChange={e => setAnswer(e.target.value)} placeholder="Type your answer"/></label><button className="action">Verify and continue <ArrowRight size={18}/></button><Link to={`/unlock-account?email=${encodeURIComponent(email)}`} className="block text-center text-sm font-semibold text-app-orange hover:underline">Can’t remember your answer? Ask our team for help</Link></form>;
  return <main className="relative min-h-screen overflow-hidden bg-[#f7f7f2] px-5 py-8 text-slate-900 sm:py-12"><div className="pointer-events-none absolute -left-24 top-8 size-80 rounded-full bg-lime-200/50 blur-3xl"/><div className="pointer-events-none absolute -right-28 bottom-0 size-96 rounded-full bg-orange-200/50 blur-3xl"/><div className="recovery-shell"><aside className="relative overflow-hidden bg-[#183b2b] p-8 text-white sm:p-12"><div className="absolute -right-14 -top-12 size-56 rounded-full border-[28px] border-lime-300/15"/><div className="relative"><div className="grid size-12 place-items-center rounded-2xl bg-lime-300 text-[#183b2b]"><ShieldCheck size={25}/></div><p className="mt-8 text-xs font-bold uppercase tracking-[.22em] text-lime-300">Grocers secure recovery</p><h1 className="mt-3 max-w-sm font-serif text-4xl leading-tight">Let’s get you back in safely.</h1><p className="mt-5 max-w-sm text-sm leading-6 text-white/70">Your account stays protected while we help you reset access in a few calm, simple steps.</p><div className="mt-10 space-y-5">{[[1,"Find your account",Mail],[2,"Confirm it’s you",CircleHelp],[3,"Choose a new password",KeyRound]].map(([n,title,Icon]) => { const I=Icon as typeof Mail; return <div key={String(n)} className={`flex items-center gap-4 ${step >= Number(n) ? "opacity-100" : "opacity-40"}`}><span className={`grid size-9 place-items-center rounded-full text-sm font-bold ${step >= Number(n) ? "bg-lime-300 text-[#183b2b]" : "border border-white/30"}`}>{step > Number(n) ? "✓" : n}</span><span><b className="block text-sm">{String(title)}</b>{step === Number(n) && <small className="text-lime-200">You are here</small>}</span><I className="ml-auto text-white/40" size={18}/></div>})}</div><div className="mt-12 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-white/75"><Sparkles className="mb-2 text-lime-300" size={18}/><b className="block text-white">Your privacy matters</b>We never show your saved answer or password to anyone.</div></div></aside><section className="flex items-center p-7 sm:p-12"><div className="mx-auto w-full max-w-md"><p className="eyebrow">{!email ? "Start recovery" : "Account recovery"}</p>{!email && <><h2 className="title mt-3">Which account needs help?</h2><p className="copy">Enter the email connected to your locked Grocers account.</p></>}{form}</div></section></div></main>;
}
