import { useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { KeyRound, ShieldCheck } from "lucide-react";
import api, { errorMessage } from "../config/api";

export default function UnlockAccount() {
  const [params] = useSearchParams(); const [email, setEmail] = useState(params.get("email") || ""); const [note, setNote] = useState(""); const [sent, setSent] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await api.post("/auth/locked-account/ticket", { email, note: note || null }); setSent(true); toast.success("Your unlock request has been sent."); } catch (error) { toast.error(errorMessage(error)); } };
  return <main className="min-h-screen bg-slate-950 px-5 py-12 text-slate-100 flex-center"><section className="w-full max-w-lg overflow-hidden rounded-2xl border border-white/10 bg-slate-900 shadow-2xl"><div className="border-b border-white/10 bg-gradient-to-r from-cyan-500/15 to-blue-500/10 p-7"><div className="grid h-12 w-12 place-items-center rounded-xl bg-cyan-400 text-slate-950"><KeyRound/></div><p className="mt-5 font-mono text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Account recovery</p><h1 className="mt-2 text-3xl font-bold">Request account unlock</h1><p className="mt-3 text-sm leading-6 text-slate-400">An employee will review your request. Once approved, you can sign in again with your existing password.</p></div>{sent ? <div className="p-7"><ShieldCheck className="text-emerald-400" size={32}/><h2 className="mt-4 text-lg font-bold">Request received</h2><p className="mt-2 text-sm leading-6 text-slate-400">Your account stays protected while the request is reviewed. We will not ask for your password.</p><Link to="/auth" className="mt-6 inline-block rounded-lg bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950">Back to sign in</Link></div> : <form onSubmit={submit} className="space-y-4 p-7"><label className="block text-sm font-medium">Account email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white outline-none focus:border-cyan-400"/></label><label className="block text-sm font-medium">Message for the employee <span className="font-normal text-slate-500">optional</span><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} placeholder="For example: I entered my password incorrectly while signing in." className="mt-1.5 min-h-28 w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-white outline-none focus:border-cyan-400"/></label><button className="w-full rounded-lg bg-cyan-400 p-3 text-sm font-bold text-slate-950 hover:bg-cyan-300">Send unlock request</button><Link to="/auth" className="block text-center text-sm text-cyan-300 hover:text-cyan-200">Back to sign in</Link></form>}</section></main>;
}
