/* eslint-disable react-hooks/exhaustive-deps */
import { NavLink, Outlet } from "react-router-dom";
import { BarChart3, ClipboardList, PackageSearch, Users } from "lucide-react";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import api, { errorMessage } from "../../config/api";
import { EmptyState, PageError } from "../../components/ApiState";
import type { Employee, InventoryRequest, ReportResult, SessionUser } from "../../types";

const links=[['/admin','Dashboard',BarChart3],['/admin/products','Products',PackageSearch],['/admin/employees','Employees',Users],['/admin/customers','Customers',Users],['/admin/requests','Requests',ClipboardList],['/admin/reports','Reports',BarChart3]] as const;
export function AdminShell(){return <div className="min-h-screen bg-app-cream"><header className="border-b bg-white p-4"><div className="mx-auto max-w-7xl font-serif text-2xl">Grocers Admin Workspace</div></header><div className="mx-auto max-w-7xl p-5 lg:flex gap-6"><aside className="mb-5 lg:w-56"><nav className="rounded-xl border bg-white p-2">{links.map(([to,label,Icon])=><NavLink end={to==='/admin'} key={to} to={to} className={({isActive})=>`flex gap-2 rounded-lg p-3 text-sm ${isActive?'bg-app-green text-white':'hover:bg-orange-50'}`}><Icon size={16}/>{label}</NavLink>)}</nav></aside><main className="flex-1"><Outlet/></main></div></div>}
export function AdminOverview(){const [metrics,setMetrics]=useState<Record<string,number>>({});useEffect(()=>{api.get('/admin/dashboard').then(({data})=>setMetrics(data.metrics||{})).catch(()=>undefined);},[]);const names=['Products','Low stock','Orders','Pending requests','Locked tickets','Funds total'];return <section><h1 className="text-3xl font-serif">Admin dashboard</h1><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{names.map((name)=><article key={name} className="rounded-xl border bg-white p-5"><p className="text-sm text-app-text-light">{name}</p><strong className="mt-2 block text-3xl">{metrics[name]??'—'}</strong></article>)}</div></section>}
export function EmployeeManagement(){const [items,setItems]=useState<Employee[]>([]);const [form,setForm]=useState({firstName:'',lastName:'',email:''});const [created,setCreated]=useState<{employeeId:string;temporaryPassword:string}|null>(null);const load=()=>api.get('/admin/employees').then(({data})=>setItems(Array.isArray(data.employees)?data.employees:[])).catch(()=>undefined);useEffect(()=>{load();},[]);return <section><h1 className="text-3xl font-serif">Employee management</h1><form onSubmit={(e)=>{e.preventDefault();api.post('/admin/employees',form).then(({data})=>{setCreated(data.credentials);setForm({firstName:'',lastName:'',email:''});load();}).catch((err)=>toast.error(errorMessage(err)));}} className="mt-5 grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><input required placeholder="First name" value={form.firstName} onChange={(e)=>setForm({...form,firstName:e.target.value})} className="border rounded-lg p-3"/><input required placeholder="Last name" value={form.lastName} onChange={(e)=>setForm({...form,lastName:e.target.value})} className="border rounded-lg p-3"/><input required type="email" placeholder="Email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} className="border rounded-lg p-3"/><button className="rounded-lg bg-app-green p-3 text-white">Add employee</button></form>{created&&<div className="mt-4 rounded-xl bg-orange-50 p-4 text-sm">Provisioned: <b>{created.employeeId}</b> · Temporary password: <b>{created.temporaryPassword}</b></div>}<div className="mt-6 space-y-2">{items.map((employee)=><article key={employee.id} className="rounded-xl border bg-white p-4 flex justify-between"><span>{employee.name} · {employee.employeeId}</span><button onClick={()=>api.delete(`/admin/employees/${employee.id}`).then(load).catch((e)=>toast.error(errorMessage(e)))} className="text-sm text-red-600">Delete</button></article>)}</div>{!items.length&&<EmptyState title="No employees" detail="Add inventory employees above."/>}</section>}
export function CustomerManagement(){const [items,setItems]=useState<SessionUser[]>([]);const [error,setError]=useState('');const load=()=>api.get('/admin/customers').then(({data})=>setItems(Array.isArray(data.customers)?data.customers:[])).catch(()=>setError('Customer management requires the Spring API.'));useEffect(()=>{load();},[]);return <section><h1 className="text-3xl font-serif">Customer management</h1>{error&&<div className="mt-4"><PageError message={error}/></div>}<div className="mt-5 space-y-2">{items.map((customer)=><article key={customer.id} className="rounded-xl border bg-white p-4 flex justify-between"><span>{customer.name} · {customer.email} {customer.locked?'(Locked)':''}</span><button onClick={()=>api.delete(`/admin/customers/${customer.id}`).then(load).catch((e)=>toast.error(errorMessage(e)))} className="text-sm text-red-600">Delete/deactivate</button></article>)}</div>{!items.length&&!error&&<EmptyState title="No customers" detail="Registered customer accounts will appear here."/>}</section>}
export function RequestQueue(){const [items,setItems]=useState<InventoryRequest[]>([]);useEffect(()=>{api.get('/admin/inventory-requests').then(({data})=>setItems(Array.isArray(data.requests)?data.requests:[])).catch(()=>undefined);},[]);const resolve=(id:string,status:string)=>api.put(`/admin/inventory-requests/${id}`,{status}).then(()=>setItems(items.map((item)=>item.id===id?{...item,status:status as InventoryRequest['status']}:item))).catch((e)=>toast.error(errorMessage(e)));return <section><h1 className="text-3xl font-serif">Employee requests</h1><div className="mt-5 space-y-3">{items.map((item)=><article key={item.id} className="rounded-xl border bg-white p-4"><b>{item.productName}</b><p className="text-sm text-app-text-light">{item.requestType}: {item.note}</p><div className="mt-3 flex gap-2"><button onClick={()=>resolve(item.id,'APPROVED')} className="text-sm text-app-green">Approve</button><button onClick={()=>resolve(item.id,'REJECTED')} className="text-sm text-red-600">Reject</button></div></article>)}</div>{!items.length&&<EmptyState title="No pending requests" detail="Employee inventory requests will appear here."/>}</section>}
export function Reports(){const [period,setPeriod]=useState('DAILY');const [kind,setKind]=useState('ORDERS');const [result,setResult]=useState<ReportResult|null>(null);const [error,setError]=useState('');const load=()=>api.get('/admin/reports',{params:{period,kind}}).then(({data})=>{setResult(data.report);setError('');}).catch(()=>setError('Reports will load after the Spring API is connected.'));useEffect(()=>{load();},[period,kind]);return <section><h1 className="text-3xl font-serif">Reports</h1><div className="mt-5 flex gap-3"><select value={period} onChange={(e)=>setPeriod(e.target.value)} className="rounded-lg border p-3"><option>DAILY</option><option>WEEKLY</option><option>MONTHLY</option></select><select value={kind} onChange={(e)=>setKind(e.target.value)} className="rounded-lg border p-3"><option>ORDERS</option><option>PRODUCT</option><option>CUSTOMER</option></select></div>{error&&<div className="mt-4"><PageError message={error}/></div>}{result&&<><div className="mt-5 grid gap-3 sm:grid-cols-3">{Object.entries(result.summary).map(([key,value])=><div key={key} className="rounded-xl bg-white border p-4"><p className="text-sm">{key}</p><b className="text-2xl">{value}</b></div>)}</div><div className="mt-5 overflow-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><tbody>{result.rows.map((row,index)=><tr key={index} className="border-b">{Object.values(row).map((value,i)=><td key={i} className="p-3">{value}</td>)}</tr>)}</tbody></table></div></>}</section>}
